services:
  rabbitmq:
    image: rabbitmq:3.13.1
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
